[package]
name = "sat-nexus"
version = "0.1.0"
authors = ["Konstantin Chukharev <lipen00@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "sys/ipasir-sys",
    "sys/cadical-sys",
]

[dependencies]
ipasir-sys = { path = "sys/ipasir-sys" }
cadical-sys = { path = "sys/cadical-sys" }
#anyhow = "1.0.40"
#eyre = "0.6.5"
color-eyre = "0.5.11"
ndarray = "0.15.2"
type-map = "0.5.0"
derive_more = "0.99.14"
snafu = "0.6.10"
itertools = "0.10.0"
tap = "1.0.1"
once_cell = "1.8.0"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
