[package]
name = "sat-nexus"
version = "0.1.0"
authors = ["Konstantin Chukharev <lipen00@gmail.com>"]
edition = "2021"

[workspace]
members = [
    "sys/cadical-sys",
    "sys/ipasir-sys",
]

[dependencies]
api = { path = "lib/api" }
ipasir = { path = "lib/ipasir" }
cadical = { path = "lib/cadical" }
wrap = { path = "lib/wrap" }

[dev-dependencies]
color-eyre = "0.5.11"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
itertools = "0.10.1"
ndarray = "0.15.3"
