[package]
name = "sat-nexus"
version = "0.1.0"
authors = ["Konstantin Chukharev <lipen00@gmail.com>"]
edition = "2021"

[workspace]
members = [
    "lib/ipasir-sys",
    "lib/minisat-sys",
    "lib/cadical-sys",
]

[dependencies]
sat-nexus-core = { path = "lib/core" }
sat-nexus-wrappers = { path = "lib/wrappers" }
ipasir = { path = "lib/ipasir" }
cadical = { path = "lib/cadical" }
minisat = { path = "lib/minisat" }

[dev-dependencies]
cadical-sys = { path = "lib/cadical-sys", features = ["dynamic", "static"] }
color-eyre = "0.6.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
itertools = "0.10.3"
ndarray = "0.15.4"
