[package]
name = "pyeda"
version = "0.1.0"
authors = ["Konstantin Chukharev <lipen00@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
pyo3 = { version = "0.23", features = ["auto-initialize"] }
