[package]
name = "cadical-sys"
version = "0.1.0"
authors = ["Konstantin Chukharev <lipen00@gmail.com>"]
edition = "2018"

[dependencies]
libloading = "0.7.0"
once_cell = "1.8.0"

[build-dependencies]
bindgen = "0.58.1"

[dev-dependencies]
glob = "0.3.0"
fs_extra = "1.2.0"
remove_dir_all = "0.7.0"
