on: [ push, pull_request ]
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

name: CI

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Set up cache
        uses: Swatinem/rust-cache@v1

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Build Cadical shared library
        working-directory: sys/cadical-sys
        run: |
          git clone --depth=1 --branch=rel-1.4.1 https://github.com/arminbiere/cadical
          cd cadical
          git apply --verbose ../cadical-shared.patch
          ./configure -fPIC
          cd build
          make -j8 libcadical.so
          sudo install -m 644 libcadical.so -Dt /usr/local/lib
          sudo ldconfig -n /usr/local/lib
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib" >> $GITHUB_ENV

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  clippy:
    name: Rustfmt and Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          # args: -- -D warnings
