name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.adoc'
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
#  build-and-test:
#    name: Build and test on Linux
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          submodules: recursive
#
#      - name: Set up Rust
#        uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: stable
#          override: true
#
#      - name: Set up cache
#        uses: Swatinem/rust-cache@v1
#
#      - name: Build
#        uses: actions-rs/cargo@v1
#        with:
#          command: build
#          args: --workspace
#
#      - name: Build and install MiniSat shared library (libminisat.so)
#        working-directory: lib/minisat-sys/vendor/minisat
#        run: |
#          cmake -B build -DCMAKE_BUILD_TYPE=Release
#          cmake --build build -- -j8
#          sudo cmake --install build --strip --prefix /usr/local
#
#      - name: Build and install MiniSat-C shared library (libminisat-c.so)
#        working-directory: lib/minisat-sys/vendor/minisat-c-bindings
#        run: |
#          make config MINISAT_INCLUDE="-I/usr/local/include"
#          make config MINISAT_LIB="-L/usr/local/lib -lminisat"
#          make config prefix=/usr/local
#          sudo make install
#
#      - name: Build and install Cadical shared library (libcadical.so)
#        working-directory: lib/cadical-sys/vendor/cadical
#        run: |
#          ./configure -fPIC
#          make -j8 shared
#          sudo install -m 644 build/libcadical.so -Dt /usr/local/lib
#
#      - name: Update ld cache and update LD_LIBRARY_PATH
#        run: |
#          sudo ldconfig -n /usr/local/lib
#          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+${LD_LIBRARY_PATH}:}/usr/local/lib" >> $GITHUB_ENV
#
#      - name: Test
#        uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: --workspace

  build-windows:
    name: Build and test on Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-14.0
      - name: Install LLVM and Clang # required for bindgen to work, see https://github.com/rust-lang/rust-bindgen/issues/1797
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Set LIBCLANG_PATH
        shell: pwsh
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable-gnu
          override: true

      - name: Set up cache
        uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Build MiniSat dynamic library
        working-directory: lib/minisat-sys/vendor/minisat
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles"
          cmake --build build
          cmake --install build --strip --prefix install
          # Result: install/bin/libminisat.dll

      - name: Build MiniSat-C dynamic library
        working-directory: lib/minisat-sys/vendor/minisat-c-bindings
        run: |
          make config MINISAT_INCLUDE="-I../minisat/install/include -I../zlib"
          make config MINISAT_LIB="-LC:/Strawberry/c/lib -L../minisat/install/lib -lminisat"
          make config prefix=install
          make install
          # Result: install/lib/libminisat-c.so (but this is actually a DLL!)

      - name: Build Cadical dynamic library
        working-directory: lib/cadical-sys/vendor/cadical
        run: |
          ./configure -fPIC
          make -j dll  2>&1
          # Result: build/cadical.dll
          ldd build/cadical.dll

      - name: Copy dynamic libraries
        run: |
          mkdir -p libs
          cp lib/minisat-sys/vendor/minisat/install/bin/libminisat.dll libs/
          cp lib/minisat-sys/vendor/minisat-c-bindings/install/lib/libminisat-c.so libs/minisat-c.dll
          cp lib/cadical-sys/vendor/cadical/build/cadical.dll libs/
          ldd libs/*.dll
          ls -al libs/*.dll
          echo "$(realpath libs)" >> $GITHUB_PATH
          # cp libs/*.dll C:/Windows

      - uses: actions/upload-artifact@v3
        with:
          name: my-dlls
          path: libs/

#      - name: Build
#        uses: actions-rs/cargo@v1
#        with:
#          command: build
#          args: --workspace

#      - name: Test
#        uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: --workspace

      - run: echo $PATH

      - name: Test 'cadical'
        continue-on-error: true
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p cadical

      - name: Test 'minisat' (dynamic)
        continue-on-error: true
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p minisat --features dynamic

      - name: Test 'minisat' (static)
        continue-on-error: true
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p minisat --features static

#  fmt:
#    name: Rustfmt
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Set up Rust stable
#        uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: stable
#          override: true
#          components: rustfmt
#
#      - name: Set up cache
#        uses: Swatinem/rust-cache@v1
#
#      - name: Run rustfmt
#        uses: actions-rs/cargo@v1
#        with:
#          command: fmt
#          args: --all -- --check
#
#  clippy:
#    name: Clippy
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          submodules: recursive
#
#      - name: Set up Rust nightly
#        uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: nightly
#          override: true
#          components: clippy
#
#      - name: Set up cache
#        uses: Swatinem/rust-cache@v1
#
#      - name: Run clippy
#        uses: actions-rs/cargo@v1
#        with:
#          command: clippy
#          args: --workspace --tests
